export const PRIDE_BADGES = [
    {
        slug: "rainbow",
        id: "8000000000000000001",
        description: "Rainbow",
        icon: "pride_rainbow",
        source: "supplemental",
    },
    {
        slug: "original-rainbow",
        id: "8000000000000000002",
        description: "Original rainbow (eight stripes)",
        icon: "pride_original_rainbow",
        source: "supplemental",
    },
    {
        slug: "philadelphia",
        id: "8000000000000000003",
        description: "Philadelphia",
        icon: "pride_philadelphia",
        source: "supplemental",
    },
    {
        slug: "progress",
        id: "8000000000000000004",
        description: "Progress",
        icon: "pride_progress",
        source: "twemoji-flags",
    },
    {
        slug: "intersex-progress",
        id: "8000000000000000005",
        description: "Intersex-inclusive Progress",
        icon: "pride_intersex_progress",
        source: "supplemental",
    },
    {
        slug: "transgender",
        id: "8000000000000000006",
        description: "Transgender",
        icon: "pride_transgender",
        source: "twemoji-flags",
    },
    {
        slug: "bisexual",
        id: "8000000000000000007",
        description: "Bisexual",
        icon: "pride_bisexual",
        source: "twemoji-flags",
    },
    {
        slug: "pansexual",
        id: "8000000000000000008",
        description: "Pansexual",
        icon: "pride_pansexual",
        source: "twemoji-flags",
    },
    {
        slug: "lesbian-five",
        id: "8000000000000000009",
        description: "Lesbian (five stripes)",
        icon: "pride_lesbian_five",
        source: "twemoji-flags",
    },
    {
        slug: "lesbian-seven",
        id: "8000000000000000010",
        description: "Lesbian (seven stripes)",
        icon: "pride_lesbian_seven",
        source: "supplemental",
    },
    {
        slug: "gay-five",
        id: "8000000000000000011",
        description: "Gay men (five stripes)",
        icon: "pride_gay_five",
        source: "supplemental",
    },
    {
        slug: "gay-seven",
        id: "8000000000000000012",
        description: "Gay men (seven stripes)",
        icon: "pride_gay_seven",
        source: "twemoji-flags",
    },
    {
        slug: "asexual",
        id: "8000000000000000013",
        description: "Asexual",
        icon: "pride_asexual",
        source: "twemoji-flags",
    },
    {
        slug: "aromantic",
        id: "8000000000000000014",
        description: "Aromantic",
        icon: "pride_aromantic",
        source: "twemoji-flags",
    },
    {
        slug: "aroace",
        id: "8000000000000000015",
        description: "Aroace (sunset)",
        icon: "pride_aroace",
        source: "twemoji-flags",
    },
    {
        slug: "agender",
        id: "8000000000000000016",
        description: "Agender",
        icon: "pride_agender",
        source: "twemoji-flags",
    },
    {
        slug: "nonbinary",
        id: "8000000000000000017",
        description: "Nonbinary",
        icon: "pride_nonbinary",
        source: "twemoji-flags",
    },
    {
        slug: "genderqueer",
        id: "8000000000000000018",
        description: "Genderqueer",
        icon: "pride_genderqueer",
        source: "twemoji-flags",
    },
    {
        slug: "genderfluid",
        id: "8000000000000000019",
        description: "Genderfluid",
        icon: "pride_genderfluid",
        source: "twemoji-flags",
    },
    {
        slug: "demiboy",
        id: "8000000000000000020",
        description: "Demiboy",
        icon: "pride_demiboy",
        source: "twemoji-flags",
    },
    {
        slug: "demigirl",
        id: "8000000000000000021",
        description: "Demigirl",
        icon: "pride_demigirl",
        source: "twemoji-flags",
    },
    {
        slug: "demigender",
        id: "8000000000000000022",
        description: "Demigender",
        icon: "pride_demigender",
        source: "twemoji-flags",
    },
    {
        slug: "demisexual",
        id: "8000000000000000023",
        description: "Demisexual",
        icon: "pride_demisexual",
        source: "twemoji-flags",
    },
    {
        slug: "demiromantic",
        id: "8000000000000000024",
        description: "Demiromantic",
        icon: "pride_demiromantic",
        source: "twemoji-flags",
    },
    {
        slug: "gray-asexual",
        id: "8000000000000000025",
        description: "Gray-asexual",
        icon: "pride_gray_asexual",
        source: "supplemental",
    },
    {
        slug: "grayromantic",
        id: "8000000000000000026",
        description: "Grayromantic",
        icon: "pride_grayromantic",
        source: "supplemental",
    },
    {
        slug: "polysexual",
        id: "8000000000000000027",
        description: "Polysexual",
        icon: "pride_polysexual",
        source: "twemoji-flags",
    },
    {
        slug: "omnisexual",
        id: "8000000000000000028",
        description: "Omnisexual",
        icon: "pride_omnisexual",
        source: "twemoji-flags",
    },
    {
        slug: "intersex",
        id: "8000000000000000029",
        description: "Intersex",
        icon: "pride_intersex",
        source: "twemoji-flags",
    },
    {
        slug: "abrosexual",
        id: "8000000000000000030",
        description: "Abrosexual",
        icon: "pride_abrosexual",
        source: "twemoji-flags",
    },
    {
        slug: "unlabeled",
        id: "8000000000000000031",
        description: "Unlabeled",
        icon: "pride_unlabeled",
        source: "supplemental",
    },
    {
        slug: "neutrois",
        id: "8000000000000000032",
        description: "Neutrois",
        icon: "pride_neutrois",
        source: "twemoji-flags",
    },
    {
        slug: "androgyne",
        id: "8000000000000000033",
        description: "Androgyne",
        icon: "pride_androgyne",
        source: "supplemental",
    },
    {
        slug: "achillean",
        id: "8000000000000000034",
        description: "Achillean",
        icon: "pride_achillean",
        source: "twemoji-flags",
    },
    {
        slug: "androsexual",
        id: "8000000000000000035",
        description: "Androsexual",
        icon: "pride_androsexual",
        source: "twemoji-flags",
    },
    {
        slug: "aspec",
        id: "8000000000000000036",
        description: "Aspec",
        icon: "pride_aspec",
        source: "twemoji-flags",
    },
    {
        slug: "ceres",
        id: "8000000000000000037",
        description: "Ceres",
        icon: "pride_ceres",
        source: "twemoji-flags",
    },
    {
        slug: "demiflux",
        id: "8000000000000000038",
        description: "Demiflux",
        icon: "pride_demiflux",
        source: "twemoji-flags",
    },
    {
        slug: "femboy",
        id: "8000000000000000039",
        description: "Femboy",
        icon: "pride_femboy",
        source: "twemoji-flags",
    },
    {
        slug: "genderflux",
        id: "8000000000000000040",
        description: "Genderflux",
        icon: "pride_genderflux",
        source: "twemoji-flags",
    },
    {
        slug: "genderqueer-symbol",
        id: "8000000000000000041",
        description: "Genderqueer (symbol)",
        icon: "pride_genderqueer_symbol",
        source: "twemoji-flags",
    },
    {
        slug: "gynesexual",
        id: "8000000000000000042",
        description: "Gynesexual",
        icon: "pride_gynesexual",
        source: "twemoji-flags",
    },
    {
        slug: "polyamory-alternative",
        id: "8000000000000000044",
        description: "Polyamory (alternative)",
        icon: "pride_polyamory_alternative",
        source: "twemoji-flags",
    },
    {
        slug: "polyamory",
        id: "8000000000000000045",
        description: "Polyamory",
        icon: "pride_polyamory",
        source: "twemoji-flags",
    },
    {
        slug: "queer",
        id: "8000000000000000046",
        description: "Queer",
        icon: "pride_queer",
        source: "twemoji-flags",
    },
    {
        slug: "sapphic",
        id: "8000000000000000047",
        description: "Sapphic",
        icon: "pride_sapphic",
        source: "twemoji-flags",
    },
    {
        slug: "straight-ally",
        id: "8000000000000000048",
        description: "Straight ally",
        icon: "pride_straight_ally",
        source: "twemoji-flags",
    },
    {
        slug: "transfeminine",
        id: "8000000000000000049",
        description: "Transfeminine",
        icon: "pride_transfeminine",
        source: "twemoji-flags",
    },
    {
        slug: "transmasculine",
        id: "8000000000000000050",
        description: "Transmasculine",
        icon: "pride_transmasculine",
        source: "twemoji-flags",
    },
    {
        slug: "abroromantic",
        id: "8000000000000000051",
        description: "Abroromantic",
        icon: "pride_abroromantic",
        source: "supplemental",
    },
    {
        slug: "aceflux",
        id: "8000000000000000052",
        description: "Aceflux",
        icon: "pride_aceflux",
        source: "supplemental",
    },
    {
        slug: "ambiamorous",
        id: "8000000000000000053",
        description: "Ambiamorous",
        icon: "pride_ambiamorous",
        source: "supplemental",
    },
    {
        slug: "androromantic",
        id: "8000000000000000054",
        description: "Androromantic",
        icon: "pride_androromantic",
        source: "supplemental",
    },
    {
        slug: "aporagender",
        id: "8000000000000000055",
        description: "Aporagender",
        icon: "pride_aporagender",
        source: "supplemental",
    },
    {
        slug: "aroflux",
        id: "8000000000000000056",
        description: "Aroflux",
        icon: "pride_aroflux",
        source: "supplemental",
    },
    {
        slug: "bigender",
        id: "8000000000000000057",
        description: "Bigender",
        icon: "pride_bigender",
        source: "supplemental",
    },
    {
        slug: "biromantic",
        id: "8000000000000000058",
        description: "Biromantic",
        icon: "pride_biromantic",
        source: "supplemental",
    },
    {
        slug: "ceteroromantic",
        id: "8000000000000000059",
        description: "Ceteroromantic",
        icon: "pride_ceteroromantic",
        source: "supplemental",
    },
    {
        slug: "ceterosexual",
        id: "8000000000000000060",
        description: "Ceterosexual",
        icon: "pride_ceterosexual",
        source: "supplemental",
    },
    {
        slug: "demifluid",
        id: "8000000000000000061",
        description: "Demifluid",
        icon: "pride_demifluid",
        source: "supplemental",
    },
    {
        slug: "diamoric",
        id: "8000000000000000062",
        description: "Diamoric",
        icon: "pride_diamoric",
        source: "supplemental",
    },
    {
        slug: "egogender",
        id: "8000000000000000063",
        description: "Egogender",
        icon: "pride_egogender",
        source: "supplemental",
    },
    {
        slug: "frayromantic",
        id: "8000000000000000064",
        description: "Frayromantic",
        icon: "pride_frayromantic",
        source: "supplemental",
    },
    {
        slug: "gender-neutral",
        id: "8000000000000000065",
        description: "Gender neutral",
        icon: "pride_gender_neutral",
        source: "supplemental",
    },
    {
        slug: "gender-questioning",
        id: "8000000000000000066",
        description: "Gender questioning",
        icon: "pride_gender_questioning",
        source: "supplemental",
    },
    {
        slug: "graygender",
        id: "8000000000000000067",
        description: "Graygender",
        icon: "pride_graygender",
        source: "supplemental",
    },
    {
        slug: "gyneromantic",
        id: "8000000000000000068",
        description: "Gyneromantic",
        icon: "pride_gyneromantic",
        source: "supplemental",
    },
    {
        slug: "hijra",
        id: "8000000000000000069",
        description: "Hijra",
        icon: "pride_hijra",
        source: "supplemental",
    },
    {
        slug: "intergender",
        id: "8000000000000000070",
        description: "Intergender",
        icon: "pride_intergender",
        source: "supplemental",
    },
    {
        slug: "maverique",
        id: "8000000000000000071",
        description: "Maverique",
        icon: "pride_maverique",
        source: "supplemental",
    },
    {
        slug: "mogai",
        id: "8000000000000000072",
        description: "MOGAI",
        icon: "pride_mogai",
        source: "supplemental",
    },
    {
        slug: "multigender",
        id: "8000000000000000073",
        description: "Multigender",
        icon: "pride_multigender",
        source: "supplemental",
    },
    {
        slug: "multisexual",
        id: "8000000000000000074",
        description: "Multisexual",
        icon: "pride_multisexual",
        source: "supplemental",
    },
    {
        slug: "neurogender",
        id: "8000000000000000075",
        description: "Neurogender",
        icon: "pride_neurogender",
        source: "supplemental",
    },
    {
        slug: "omniromantic",
        id: "8000000000000000076",
        description: "Omniromantic",
        icon: "pride_omniromantic",
        source: "supplemental",
    },
    {
        slug: "pangender",
        id: "8000000000000000077",
        description: "Pangender",
        icon: "pride_pangender",
        source: "supplemental",
    },
    {
        slug: "panromantic",
        id: "8000000000000000078",
        description: "Panromantic",
        icon: "pride_panromantic",
        source: "supplemental",
    },
    {
        slug: "polygender",
        id: "8000000000000000079",
        description: "Polygender",
        icon: "pride_polygender",
        source: "supplemental",
    },
    {
        slug: "polyromantic",
        id: "8000000000000000080",
        description: "Polyromantic",
        icon: "pride_polyromantic",
        source: "supplemental",
    },
    {
        slug: "pomosexual",
        id: "8000000000000000081",
        description: "Pomosexual",
        icon: "pride_pomosexual",
        source: "supplemental",
    },
    {
        slug: "transneutral",
        id: "8000000000000000082",
        description: "Transneutral",
        icon: "pride_transneutral",
        source: "supplemental",
    },
    {
        slug: "trigender",
        id: "8000000000000000083",
        description: "Trigender",
        icon: "pride_trigender",
        source: "supplemental",
    },
    {
        slug: "two-spirit",
        id: "8000000000000000084",
        description: "Two-spirit",
        icon: "pride_two_spirit",
        source: "supplemental",
    },
    {
        slug: "waria",
        id: "8000000000000000085",
        description: "Waria",
        icon: "pride_waria",
        source: "supplemental",
    },
    {
        slug: "xenogender",
        id: "8000000000000000086",
        description: "Xenogender",
        icon: "pride_xenogender",
        source: "supplemental",
    },
] as const;

const PRIDE_BADGE_ALIASES: Record<string, string[]> = {
    rainbow: ["pride", "lgbt", "lgbtq", "lgbtqia", "gay"],
    "original-rainbow": ["pride", "lgbt", "gilbert baker"],
    philadelphia: ["pride", "lgbt"],
    progress: ["pride", "lgbt", "lgbtqia"],
    "intersex-progress": ["pride", "lgbt", "lgbtqia"],
    "straight-ally": ["ally"],
    nonbinary: ["non-binary", "non binary", "enby"],
    polyamory: ["polyamorous", "poly"],
    "polyamory-alternative": ["polyamorous", "poly"],
    androgyne: ["androgynous"],
    "gay-five": ["gay men", "mlm"],
    "gay-seven": ["gay men", "mlm"],
    "lesbian-five": ["wlw"],
    "lesbian-seven": ["wlw"],
    aspec: ["a-spec", "ace spectrum", "aro spectrum"],
    asexual: ["ace"],
    aromantic: ["aro"],
    "gray-asexual": ["grey-asexual", "graysexual", "greysexual"],
    graygender: ["greygender"],
    grayromantic: ["greyromantic"],
    transgender: ["trans"],
    hijra: ["hijara"],
    "two-spirit": ["two spirit", "2s"],
};

export const PRIDE_BADGE_CATALOG = PRIDE_BADGES.map((badge) => ({
    ...badge,
    aliases: PRIDE_BADGE_ALIASES[badge.slug] ?? [],
}));

export const prideBadges = (selected: readonly string[] | null | undefined) =>
    [...new Set(selected ?? [])].flatMap((slug) => {
        const badge = PRIDE_BADGES.find((item) => item.slug === slug);
        return badge ? [{ id: badge.id, description: badge.description, icon: badge.icon }] : [];
    });
