export type IpDataIpLookupResponse = typeof ipDataSampleIpLookupResponse;

const ipDataSampleIpLookupResponse = {
    ip: "",
    is_eu: true,
    city: "",
    region: "",
    region_code: "",
    country_name: "",
    country_code: "",
    continent_name: "",
    continent_code: "",
    latitude: 0,
    longitude: 0,
    postal: "",
    calling_code: "",
    flag: "",
    emoji_flag: "",
    emoji_unicode: "",
    asn: {
        asn: "",
        name: "",
        domain: "",
        route: "",
        type: "isp",
    },
    languages: [
        {
            name: "",
            native: "",
        },
    ],
    currency: {
        name: "",
        code: "",
        symbol: "",
        native: "",
        plural: "",
    },
    time_zone: {
        name: "",
        abbr: "",
        offset: "",
        is_dst: true,
        current_time: "",
    },
    threat: {
        is_tor: false,
        is_icloud_relay: false,
        is_proxy: false,
        is_datacenter: false,
        is_anonymous: false,
        is_known_attacker: false,
        is_known_abuser: false,
        is_threat: false,
        is_bogon: false,
        blocklists: [],
    },
    count: 0,
    status: 200,
};
